export const cohortData = [
    {
      "GH_NAME": "claddyy",
      "First name": "Mohit",
      "Last name": "Kumar",
      "Email": "0xcladdy@gmail.com",
      "Discord Username": "claddyy",
      "Background": "I'm claddy and I've been a part of Summer of Bitcoin 2023 where I contributed to `eclair` and I was mentored by Bastien Teinturier(t-bast). I continued my journey and read Mastering Bitcoin and Programming Bitcoin. I also contributed to some bitcoin FOSS projects and picked up Rust as my go-to language.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "ABD-AZE",
      "First name": "Abdullah",
      "Last name": "Azeem",
      "Email": "abdullahazeem770@gmail.com",
      "Discord Username": "abdaze",
      "Background": "Education: CSE @ IIT Roorkee\nSkills:c/c++,Go, Rust Javascript, ZK SNARKS, Solidity , Git , foundry,computer Architecture\nAwards: 1st prize socket protocol | EthIndia 2024, 2nd prize polygon zkevm | EthIndia 2024, Winner | Based India 2024",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "Aditaya08",
      "First name": "Aditaya",
      "Last name": "Sharma",
      "Email": "aditayash625@gmail.com",
      "Discord Username": "aditaya",
      "Background": "2nd yr b.tech in cs major specialising in blockchain currently exploring different blockchains and want to do dive deeper in some like bitcoin using rust solana and aptos .also want to explore sui and polygon but to be precise I am just learning random stuff .  would want a structured path to follow to become an open source contributor . Also desperately in need of internship coz its getting difficult to manage . i have almost basic knowledge of rust . i have done data structures using cpp I did s minor smart auction contract using solidity part from that I made a java minor project of quiz app in rust I made a guessing game through the guidance of the rust programming lang book  I also have almost entire theoretical knowledge of blockchain  what I really want is to how to write os code and how to code to earn money",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "hax0kartik",
      "First name": "Kartik",
      "Last name": "Agarwala",
      "Email": "Agarwala.kartik@gmail.com",
      "Discord Username": "hax0kartik",
      "Background": "Ever since childhood, I have had a passion for tinkering and learning how computers operate at a fundamental level. I liked “modding” whatever game console I had so that I could play around with its internals more. The first app I created was a simple drawing program for Nintendo 3DS when I was 12. My curiosity about the console led me to contribute more to the homebrew scene, which honed and improved my programming skills. Members of the 3DS scene introduced me to Open-source software, and since then I have created and worked on multiple OSS projects. \n\nOver the years, I have had the opportunity to contribute to many OSS projects. In 2019, I participated in Google Code-In and contributed to the Network Simulator 3 project, for which I was declared the Grand Prize Winner. Recently in 2023, I participated in Google Summer of Code with the ScummVM organization and in 2024, I got selected as a LFX mentee to work on fixing Linux kernel bugs and I also got selected in a GSoC-like program called Summer of Bitcoin, where I applied differential fuzzing to uncover bugs in different bitcoin implementations. Other than this, I have contributed to Miasm, libctru, ZoneMinder and other popular projects.\n\nI primarily code in C or C++ and have successfully undertaken projects in various fields such as systems programming, embedded development, security research and applications, and game development.\n \nI developed my interest in bitcoin during my Summer of Bitcoin programme where I learnt a lot more about bitcoin. I worked under Bruno Garcia to develop bitcoinfuzz, in which we applied differential fuzzing to different bitcoin implementations. We were able to discover several bugs and even uncovered a CVE with rust-miniscript.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "jkciw",
      "First name": "Bala",
      "Last name": "C",
      "Email": "balaji.c.86@gmail.com",
      "Discord Username": "bala_111",
      "Background": "I am an electrical engineer by education and have been studying about the technical aspects of bitcoin since a couple of years. I have been contributing to a FOSS project called CoinSelection, incubated by Bithsala. I am familiar with rust and working to improve my rust skills.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "basantagoswami",
      "First name": "Basanta",
      "Last name": "Goswami",
      "Email": "basantagoswami1999@gmail.com",
      "Discord Username": "basantagoswami",
      "Background": "I am a web developer, have some experience working with IoT stuff in C++. I have need doing nostr stuff for a while now. I have read Mastering Bitcoin and also go through parts of Programming Bitcoin.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "BEULAHEVANJALIN",
      "First name": "Beulah",
      "Last name": "Evanjalin",
      "Email": "beulahebenezer777@gmail.com",
      "Discord Username": "beulahevanjalin",
      "Background": "I am a software developer with a strong background in Mathematics and Computer Science. Skilled in Java, JavaScript, TypeScript, Python, C and R. I specialize in backend development using technologies like Spring Boot, Node.js, PostgreSQL, and Docker. My professional interests include solving complex problems in distributed systems and blockchain with a particular focus on Cryptography.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "dhirajs0",
      "First name": "Dhiraj",
      "Last name": "Sah",
      "Email": "dhiraj.kumar2990@gmail.com",
      "Discord Username": "dhirajs0",
      "Background": "I am currently working at Sears Holdings as a Software Engineer-II.  July-2024 - Present\nAt sears, I am part of Sears KAIros team working on developing AI agents and automation.\nTech Used: Python, FastAPI, AI-Agents\n\nI have worked at Samsung Research & Development, India  as a Software Engineer - June 2022–June 2024\nAt Ssamsung I worked at Tizen TV SDK team, that develops tools for developing applications for Tizen OS. I was also part of a feasibility study of the intruction of rust for Tizen OS.\nTech Used: Rust, C++, Python, Django  \n\nEduction:\nI did my Bachelor's in Technology (in Computer Science) at Indian Institute of Information Technology. July 2018–May 2022",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "Dsiddhart",
      "First name": "Siddharth",
      "Last name": "Dubey",
      "Email": "dsiddharth4295@gmail.com",
      "Discord Username": "sid07_2003",
      "Background": "Currently I am in my 3rd year of bachelor of technology from Indian Institute of technology (BHU),VARANASI. Earlier I did backend in NodeJs, used React.js framework for frontend, for database I had done mongoose, jwt authentication.Apart from this I also Built a prediction market enabling users to forecast ETH/USD price movements and earn rewards for accurate\n predictions, integrating off-chain data through hermes.pyth.network, so for this project I made erc20 token contract , made decentralized exchange contract,and a prediction contract where is the main reward logic is present. But I used a lot of documentation help to built it , as I made this is in solidity which I had no prior knowledge i took the of gpt for the syntax , but this project had sparked my interest towards this field,  so this is all I got.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "Kenya",
      "Cohort": "India"
    },
    {
      "GH_NAME": "Aybee5",
      "First name": "Ibrahim",
      "Last name": "Abdullahi",
      "Email": "ibrahimabdul050@gmail.com",
      "Discord Username": "ibrahim050",
      "Background": "I holds degree in Computer Science from Bayero University Kano(Nigeria) and have over 6 years of experience in computer programming working primary with JavaScript/TypeScript. I am currently enrolled in MSc Cyber Security.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "MachoMaheen",
      "First name": "Maheen",
      "Last name": "K",
      "Email": "kabeermaheen6@gmail.com",
      "Discord Username": "maheenk",
      "Background": "I am Maheen K, a senior undergraduate student in Computer Science and Engineering at the College of Engineering, Trivandrum, with a GPA of 8.34. My journey in tech started with a strong foundation in programming and problem-solving, which I’ve built upon by exploring blockchain development, smart contracts, and open-source contributions.\n\nFor most of my blockchain development years, I focused on the Ethereum ecosystem, working on projects like Certify-ETH, a secure blockchain-based platform for digital certifications, and Stark-Pilot, a VS Code extension for StarkNet that integrates AI-powered tools to enhance developer productivity. I’ve participated in prominent hackathons like ETHIndia, ETHDenver, and StarkHack, showcasing my ability to innovate and build in collaborative environments.\n\nI also bring experience in web2 development, having contributed to open-source projects and freelanced as a developer. My technical toolkit includes proficiency in C++, Rust, Solidity, and JavaScript, alongside tools and frameworks like Hardhat, React, and Next.js. I’ve led technical teams, such as the IEDC Summit’23 tech team, managing applications for over 7,500 participants.\n\nWhile my open-source contributions have primarily been in web2, I’m now deeply motivated to contribute to Bitcoin’s open-source ecosystem.I was shortlisted for the Summer of Bitcoin program, though I couldn’t complete my task due to personal and college commitments. These experiences reinforced my determination to grow in this field.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "keraliss",
      "First name": "kera",
      "Last name": "liss",
      "Email": "keralis1131f@gmail.com",
      "Discord Username": "keraliss",
      "Background": "Computer Science graduate (2022) specializing in web and front-end development, with working knowledge of back-end and Rust programming.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "USA",
      "Cohort": "India"
    },
    {
      "GH_NAME": "Lakshyyaa",
      "First name": "Lakshya",
      "Last name": "Singh",
      "Email": "lakshh113@gmail.com",
      "Discord Username": "lakshh113",
      "Background": "Have primarily worked as a full-stack developer in startups and good with C++ and data structures. Recently I have been spending time learning rust and focussed on building low-level backends. Had less technical knowledge of bitcoin until the assignment and ready to dive deep and code for bitcoin FOSS itself. Currently a new-grad in CS and always looking for cool stuff to build/explore and prefer spending my time learning/reading. And above all I find working on bitcoin really cool so that is another thing (among many) that brought me here. Hoping to get in!",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "mihir1739",
      "First name": "Mihir",
      "Last name": "Kumar Singh",
      "Email": "mihir39nr@gmail.com",
      "Discord Username": "mahakaal17",
      "Background": "I have a keen interest in bitcoin and looking for ways to contribute into the same. I had started my programming journey with python. Then I learnt web technologies as Javascript and NodeJS. I have experience in backend part with NodeJS and Databases.Then I leapt on kernel level programming in CPP. That is my current work as a software engineer. I have also worked with Rust in bitcoin and built projects around the same.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "Gmin2",
      "First name": "Mintu",
      "Last name": "Gogoi",
      "Email": "mintugogoi567@gmail.com",
      "Discord Username": "gmintu",
      "Background": "I'm a software developer with two years of experience maintaining the AsyncAPI Generator project and contributing to various open source projects.I am currently looking at the rust-bitcoin github repository to gain a deep understanding of the codebase and how it is implemented",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "sarvalabs-karthik",
      "First name": "Karthik Kumar Reddy",
      "Last name": "Nallabolu",
      "Email": "nallaboluk@gmail.com",
      "Discord Username": "karthik340",
      "Background": "I am working as core protocol engineer at sarva labs where i work on consensus, txpool, syncer and multiple modules. I use golang on day to day basis.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "PaarthAgarwal",
      "First name": "Paarth",
      "Last name": "Agarwal",
      "Email": "paarthagarwal551@gmail.com",
      "Discord Username": "paarth0370",
      "Background": "I'm a seasoned open-source developer who contributed significantly to FOSS through internships. I've been a Google Summer of Code mentee with Wagtail, where I spent my time implementing and reducing the carbon footprint of Wagtail sites. My second Google Summer of Code was with Data for Common Good, where I assessed the viability of the new GEN3 frontend framework. I've also contributed to CNCF under the LFX mentorship program with CNCF Harbor and have mentored interns in a similar program called Outreachy.\nI've been a part of many open-source communities and part of my college's programmers club. Most of my work has been in the web development domain, and some have been in DevOps. I also contributed to a Python-based crypto wallet by Specter Solutions last year. I wish to improve my Rust skills and develop something cool through this program.\n\nAdditional note: I've worked with teams in different timezones before and am perfectly comfortable with accommodating late-night or early-morning calls. Thanks!",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "Parth401101",
      "First name": "Parth",
      "Last name": "Shah",
      "Email": "parth401101@gmail.com",
      "Discord Username": "parth_401101",
      "Background": "I initially became interested in decentralized finance (DeFi) and gained some knowledge about smart contracts. Through exploring DeFi, I discovered Bitcoin Core development and became deeply fascinated by its robust design and foundational role in the cryptocurrency space. To build a strong understanding, I'm about to complete Mastering Bitcoin by Andreas Antonopoulos.\n\nI have beginner-level technical experience, primarily in C++ programming. While my coding background is currently basic, I am committed to improving it through hands-on learning and practice.\n\nI am excited to participate in Chaincode Labs’ learning program, where I aim to develop my skills in Bitcoin and Lightning development while contributing meaningfully to the ecosystem. My primary focus is on learning, growing technically, and collaborating with experts to gain the expertise needed for impactful contributions",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "rishkwal",
      "First name": "Rishabh",
      "Last name": "K",
      "Email": "rishkwal@gmail.com",
      "Discord Username": "rishkwal",
      "Background": "I have completed my four year undergraduate in Electronics and Instrumentation in 2024. I have been programming for about 5 years now. Started with Web Development and the JavaScript ecosystem, stuck with it for a long time and have recently started exploring lower level programming with Rust. I got introduced to Bitcoin in 2021 via the Summer of Bitcoin program and have been working on and off on Bitcoin related projects since. I currently contribute to Coinswap(https://github.com/citadel-tech/coinswap) mostly on the research and protocol development side.\nI am fairly proficient in Full stack Development with JavaScript(React, Node, etc) and Scaling Web Applications and DevOps.\nI consider myself a beginner in Rust but proficient enough to be able to contribute to a Rust project. I am comfortable with the technical details of Bitcoin and have also completed the Mastering Bitcoin cohort by Bitshala, finishing as a top performer(https://rishabh.wiki/posts/bitshala-mastering-bitcoin-cohort-review/).",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "Thailand",
      "Cohort": "India"
    },
    {
      "GH_NAME": "kaneki003",
      "First name": "Saksham",
      "Last name": "Chauhan",
      "Email": "sakshamchauhan707@gmail.com",
      "Discord Username": "kaneki00_3",
      "Background": "I am a B.Tech student in ECE at IIT (BHU), Varanasi. I have expertise in programming languages like C++, Python, and JavaScript, and frameworks such as ReactJS and MongoDB. I have worked on impactful projects like ChainGamble, a blockchain-based betting platform, and an online marketplace. As an active member of programming and tech clubs, I bring strong technical and collaborative skills, complemented by notable achievements in academics and competitions.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "shubh9598",
      "First name": "Anant pratap",
      "Last name": "singh",
      "Email": "sanantpratap879@gmail.com",
      "Discord Username": "anantpratapsingh",
      "Background": "I am pursuing a dual degree (B.Tech + M.Tech) in Engineering Physics (4th year) and have a strong passion for programming, particularly in competitive programming. With a Codeforces rating of 1669 and a 4-star rating on CodeChef, I have honed my problem-solving skills and enjoy designing efficient algorithms to tackle complex challenges.\n\nMy primary language for competitive programming is C++, where I focus on writing optimized and effective solutions. Additionally, I have hands-on experience with the MERN stack, enabling me to build dynamic and responsive web applications.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "0xEgao",
      "First name": "Sarthak",
      "Last name": "Arora",
      "Email": "sarthakarora616@gmail.com",
      "Discord Username": "0xegao",
      "Background": "I am an undergrad doing a computer major right now, and have been exploring about different blockhains lately(past 5-6months) and came up about this program. On the technical side, I have experience of full stack development, exploring rust since couple of months , created some easy-med projects in it, currently reading the book \"Building bitcoin in rust\" which helping me to sharpen me more in rust as well as dive deeper into Bitcoin at the same time. I spend a lot of time studying about bitcoin and other few blockchain technologies in my day to day life, and eager to learn about it more and contribute to the community.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "cakesoft-shashank",
      "First name": "Shashank",
      "Last name": "Shinde",
      "Email": "shashank.shinde@live.com",
      "Discord Username": "shashi4",
      "Background": "I am a full stack developer specializing in React Native with proficiency in TypeScript, JavaScript. Currently, I am working on Bitcoin Tribe and Bitcoin Keeper. In addition to my work with React Native, I have experience with Rust, as some of our modules are written in it.I also have working knowledge of Go, C++, Kotlin, and Java.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "funyug",
      "First name": "Shivam",
      "Last name": "Chawla",
      "Email": "shivamchawla243@gmail.com",
      "Discord Username": "funyug",
      "Background": "I am a software engineer from New Delhi, India. I have been working as a backend engineer for 10 years. I have experience with JavaScript, Golang and PHP. I got introduced to Bitcoin in 2014 and did some freelancing jobs in the industry till 2015 but stopped focusing on it from development perspective. Got back into crypto in 2021 and joined a wallet infrastructure Liminal Custody as principal engineer and was working there till October 2024. Currently taking a break for 6 months and thinking of joining a bitcoin only startup after the break.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "shivanshuraj1333",
      "First name": "Shivanshu",
      "Last name": "Raj Shrivastava",
      "Email": "shivanshu1333@gmail.com",
      "Discord Username": "shivanshu1333",
      "Background": "I have been working professionally for 5 years building infrastructure (kubernetes, istio) and observability (opentelemetry, custom agents) tools. I have worked at big tech companies and a couple of US startups. I am currently working at a YC company as a founding engineer. I have a decent experience in Java and Golang, and for past one year, I have been learning rust, and now comfortable with it. But till date I haven't wrote a a code which is running in production in Rust, mostly all my production work is either in Java or Golang.\nYears ago, I got introduced to chaincode and bitcoin core codebase. Yet, I haven't made any significant contribution to the ecosystem. With this program, I aim to get in touch with like minded people, and learn from them. I am aiming to become a contributor by the end of the program.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "notTanveer",
      "First name": "Tanveer",
      "Last name": "-",
      "Email": "tanveer.x.ansari@gmail.com",
      "Discord Username": "tanveer5523",
      "Background": "I’ve been working on the implementation of Silent Payments for over four months, using TypeScript. While this has been effective so far, I’m aware that relying on TypeScript might limit scalability in the long run. My goal is to develop an indexer in Rust, as it offers better performance and scalability for the project.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "psyberfly",
      "First name": "Anorak",
      "Last name": "Doe",
      "Email": "travisbickle27@proton.me",
      "Discord Username": "anorakk8",
      "Background": "I'm a software engineer developing web services for 2.5 years now. I've been associated with Bitcoin for a year now. I currently work with Bull Bitcoin. For the last 6 months I've been developing their Bitcoin exchange API and maintaining two staging servers. The last month I've shifted my work to mainly focus on their European exchange web app. I work mostly with Typescript, Dart, Docker, Linux and other open source tools.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "Levi0804",
      "First name": "Vansh",
      "Last name": "Dassani",
      "Email": "vansh.dassani10@gmail.com",
      "Discord Username": "levi0804",
      "Background": "I'm a 20 year old B.Tech student studying computer science with a growing interest in blockchain technology. I’ve recently contributed to Aptos core and developer docs which has been a great learning experience for me. I am also learning and building with Rust and I enjoy exploring how it can be used in blockchain projects. I'm really interested in contributing to the Bitcoin ecosystem and expanding my understanding of its architecture.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "VanshulB",
      "First name": "Vanshul",
      "Last name": "Bhatia",
      "Email": "vanshulbhatia@gmail.com",
      "Discord Username": "vanshul",
      "Background": "I have been doing Rust since the beginning of 2024, and I was selected for the Summer of Bitcoin 2024 in Lampo, where I worked to integrate VLS into Lampo. In addition, I previously worked as a Software Developer Intern at Mastercard India.\nI have been doing Rust Development for the past 4-5 months rigorously (not specifically bitcoin focused, but general software development in rust). I would like to contribute to Rust specifics projects in the upcoming BOSS program!",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "infinite-time",
      "First name": "Vinay",
      "Last name": "V",
      "Email": "vinayv1234@gmail.com",
      "Discord Username": "vinayv1234",
      "Background": "Technical & management roles in distributed systems and medical imaging.  C++, C#, Java etc",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "KnowWhoami",
      "First name": "Divyansh",
      "Last name": "Gupta",
      "Email": "whoamilinux987@gmail.com",
      "Discord Username": "know_whoami",
      "Background": "I have been working in Bitcoin since last year.\nTill Now , I have worked in various bitcoin open source projects lilke Fedimint, Rust-Bitcoin,Bitcoin Dev Kit(BDK) and Coinswap.\nMost of my contributions  are for Coinswap and now I am part of its core-team.\nI am mainly focused on Rust and thus only contributes in rust-based bitcoin projects.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "YoganshSharma",
      "First name": "Yogansh",
      "Last name": "Sharma",
      "Email": "yoganshsharma65@gmail.com",
      "Discord Username": "yogansh.",
      "Background": "-  Undergraduate at IIT Kharagpur.\n- Currently focused on learning and working with Rust and Bitcoin.\n- Passionate about open source, Nix, Linux and of course Bitcoin.\n\n- Experienced with backend web development and DevOps.\n-  Executive Head at Kharagpur Open Source Society: organized Kharagpur Winter of Code  (KWoC) 2023 and currently organizing KWoC 2024, where I rewrote the backend with Golang, and implemented CI/CD pipelines.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "i-am-yuvi",
      "First name": "yuvic",
      "Last name": "yuvic",
      "Email": "yuvichh01@gmail.com",
      "Discord Username": "iamyuvi",
      "Background": "Before entering Bitcoin, I was already in the Backend Development field contributing to open-source projects such as Kubernetes, Jenkins, and Jenkins-x. I was also a part of Code For Govt Tech. I am very much active in X(prev. Twitter) and often write blogs for the newbie folks such as tutorials, changes, etc. Apart from this, I was also a Chief Creative Officer a.k.a ambassador at Showwcase. Currently, I am also a part of Summer of Bitcoin intern working at Bitcoin Core(peer-observer, anomaly detection in Bitcoin P2P Network)\n\nBefore the Summer of Bitcoin, I didn’t have any deep knowledge of Bitcoin, I was just curious to learn about “Why we can’t hack Bitcoin?”, silly I didn’t know the maths behind it. Speaking about my work in Bitcoin, I have reviewed some PRs and read some research papers regarding the Bitcoin p2p network which include:\n\n[Peer-observer](https://github.com/0xB10C/peer-observer.git): monitor your peers, LinkingLion Connections\nLearnt Rust through Rust for Bitcoiners cohort and contributed to peer-observer during my free time. Some of my contributions include #25, #29, #30 and WIP #36 and Detecting SPY Peers.\nAlso, I have written a detailed article on Peer-Observer, setting it up is tedious as some of the PR(#25832) are currently under review and also require root system privileges. \n\nTracing in Bitcoin Core\nTracing typically involves capturing and recording information about the system to debug or perform a real-time analysis of the system. It helps identify bugs in the system. I have reviewed and tested various PRs in Tracing which include #19866, #22006, #25832, and #26593. \nI have written a detailed article on it, you can see here.\nAnomaly Detection in Bitcoin P2P Network (Issue #13)\nThis describes a system for monitoring the peer-to-peer (P2P) network of a Bitcoin Network. The goal is to detect anomalies or unusual activity that could indicate potential issues or attacks on the network. All the updates to the Anomaly Detection using peer-observer can be seen in the issue tracking and discord(Summer of Bitcoin) public channel as well!!\n\nAlgorithms that are being used:\n\nZ-score: This looks at the overall inbound and outbound connections across all nodes to detect when the network activity deviates significantly from the normal or expected patterns.\nMod Z-score (Modified Z-score): This is used to detect anomalies at the individual node level, as it is more sensitive to changes in a single node's inbound/outbound connections.\nThe key outcomes and observations from the anomaly detection system include:\nIdentifying issues with certain \"ARM nodes\" that had high CPU usage and would frequently restart, causing drops in inbound connections.\nDetecting an attack on the \"Alice\" node that was overloaded by Bloom filter requests, exposing a potential DoS vulnerability.\nIdentifying dips in inbound connections for individual nodes, which were sometimes caused by nodes syncing with the blockchain or running out of disk space.\nHighlighting the differences between using the overall Z-score vs the more sensitive Mod Z-score for detecting anomalies at the individual node level.\nDiscussions around the relative merits of using rate tests vs derivative tests for monitoring address-related metrics.\nThe report has been attached here [https://docs.google.com/document/d/1FE5wJrx4sWy46m_QAe0-j1c9w2l4AkDUdNziXb29Un8/edit#bookmark=id.hlmx7zs1usyj]\n\n\nCurrently I am working at Bitshala, wherein I am reviewing the PR's of Bitcoin Core. Additionally, I am also working on the issues related to P2P and tests part of Bitcoin Core.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "zaidmstrr",
      "First name": "Mohd",
      "Last name": "Zaid",
      "Email": "zaidbrock90@gmail.com",
      "Discord Username": "zaidmstrr",
      "Background": "I’m currently in the final year of the “Master of Computer Applications” (MCA) degree program, and I have done a Bachelor of Computer Applications (BCA). So I have some technical experience, and through my degree program, I worked on many things, like creating web applications using MERN, including chat applications, games, course-selling applications, and cloud deployment using AWS. I also learned many programming languages, for example, C/C++, Java, JavaScript, and Python for artificial intelligence and machine learning using different libraries in Python for data filtering and analysis. I also trained some basic AI models using Python, like desktop assistants. I also worked on implementing data structures and algorithms to solve different challenges and puzzles and am still studying theoretical data structures. Since my school, I was very interested in cybersecurity; that’s why I opted for my first course in “Ethical Hacking and Web Penetration Testing” in my 10th grade and explored this field by testing web apps for several OWASP top 10 vulnerabilities like cross-site scripting (XSS), SQL injection, clickjacking, remote code execution, etc.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "Prabhat1308",
      "First name": "Prabhat",
      "Last name": "Verma",
      "Email": "p_verma1@ece.iitr.ac.in",
      "Discord Username": "pr0b0t1sc00l",
      "Background": "I am actively involved in Bitcoin development. Was a past participant of the FOSS program and I am an alumni of the Summer of Bitcoin 24 program having done it under Bitcoin core org. Currently I am a fellow under Bitshala",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "sandipndev",
      "First name": "Sandipan",
      "Last name": "Dey",
      "Email": "hey@sandipan.dev",
      "Discord Username": "sandipndev",
      "Background": "Rust, Typescript dev. Summer of Bitcoin 2021. Experienced in event sourcing and domain driven design patterns. I have good experience in DevOps roles, managing and deploying kubernetes clusters with proper CI/CD. Working on using bitcoind / at third party apps layer; I’m trying to pivot towards more bitcoin protocol layer work. Or designing libraries at the protocol level.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "rustlamp",
      "First name": "Rust",
      "Last name": "Lamp",
      "Email": "rustlamp@tutamail.com",
      "Discord Username": "rustlamp",
      "Background": "Working as rust engineer, and would like to get into bitcoin much deeper",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "chaitika",
      "First name": "Chaitika",
      "Last name": "Bhatnagar",
      "Email": "chaitika92@gmail.com",
      "Discord Username": "chaitika",
      "Background": "I am currently pursuing my Master's in Computer Applications with a strong foundation in programming and design. My technical skills include Java, C,C++, JavaScript, and React, with hands-on experience in building applications. Apart from my technical work, I actively engage in mentoring, organizing events, and leading student initiatives. I'm passionate about tech and design, always seeking to enhance my skills and make an impact!",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "soloking1412",
      "First name": "Maheswaran",
      "Last name": "Velmurugan",
      "Email": "maheswar141203@gmail.com",
      "Discord Username": "soloking1412",
      "Background": "I am a blockchain developer with over three years of experience building in the web3 space, including developing DeFi platforms, yield farming solutions, and DEXs on Solana and EVM-compatible chains. As a co-founder and entrepreneur, I combine technical expertise with business development skills, supported by strong foundations in security from courses like Cyfrin Updraft and hands-on CTF challenges. My journey spans roles such as node operator, community manager, and ambassador, offering a well-rounded perspective on blockchain ecosystems.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    },
    {
      "GH_NAME": "110CodingP",
      "First name": "codingp110",
      "Last name": "codingp110",
      "Email": "codingp110@gmail.com",
      "Discord Username": "codingp110",
      "Background": "I am a math undergrad who has fallen down the Bitcoin rabbit hole. While I am a beginner in software development, I love both development and Bitcoin. \nSo far I have gone through Grokking Bitcoin, Learning Bitcoin from the Command Line and Bitcoin Protocol Development. Due to coursework, I have some experience with C , C++ and Python. I am currently going through Bitcoiner's Intro To Rust and Programming Bitcoin.",
      "Time Zone in UTC": "UTC + 5:30",
      "Country": "India",
      "Cohort": "India"
    }
  ]